FROM ubuntu:18.04
MAINTAINER eltno84 <ghcetraro@gmail.com>

# Install 
RUN apt-get update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    apache2 curl nano net-tools telnet

RUN mkdir -p /etc/apache2/ssl/
COPY linux.* /etc/apache2/ssl/
COPY registry_v2.conf /etc/apache2/sites-enabled/
COPY site.conf /etc/apache2/sites-enabled/

RUN echo "ServerName apache" >> /etc/apache2/apache2.conf

RUN a2dissite 000-default.conf

# Enable apache mods.
RUN a2enmod rewrite
RUN a2enmod proxy*
RUN a2enmod ssl
RUN a2enmod headers

# Manually set up the apache environment variables
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

# Expose apache.
EXPOSE 80

# By default start up apache in the foreground, override with /bin/bash for interative.
CMD /usr/sbin/apache2ctl -D FOREGROUND

